sudo: required
services:
  - docker

before_install:
  - docker build -t yixinxie/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yixinxie/react-test npm test -- --coverage

after_success:
  - docker build -t yixinxie/multi-client -f ./client/Dockerfile ./client
  - docker build -t yixinxie/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t yixinxie/multi-server -f ./server/Dockerfile ./server
  - docker build -t yixinxie/multi-worker -f ./worker/Dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yixinxie/multi-client
  - docker push yixinxie/multi-nginx
  - docker push yixinxie/multi-server
  - docker push yixinxie/multi-worker